Repository EmilBurman/Java_TestAutomationFramework, pull requests merged in 2020-03, with the labels that each got.

#8 Fix
  .github/label-pr.yml
  .github/workflows/gradle.yml
  .gitignore
  build.gradle
  gradle.properties
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  src/main/resources/api.secrets.properties
  src/test/java/framework/api/services/omdb/GetTitle_api_test.java
Labels: code, configuration, gradle

#9 large refactor for builder pattern
  src/main/java/framework/adapters/HTTPadapter.java
  src/main/java/framework/api/services/UriRequest.java
  src/main/java/framework/api/services/cat/CatServiceManager.java
  src/main/java/framework/api/services/omdb/OmdbServiceManager.java
  src/main/java/framework/api/services/utils/CatTags.java
  src/main/java/framework/api/services/utils/OmdbTags.java
  src/main/java/framework/utils/JsonUtils.java
  src/main/java/framework/utils/PropertyUtils.java
  src/main/resources/api.secrets.properties
  src/main/resources/env.produktion.api.properties
  src/test/java/framework/api/services/cat/GetFact_api_test.java
  src/test/java/framework/api/services/omdb/GetTitle_api_test.java
  src/test/java/framework/behaviordriven/services/cat/StepDefinitionsCat.java
Labels: code, configuration

#10 Facade strategy pattern
  src/main/java/framework/ApiManagementInterface.java
  src/main/java/framework/adapters/HTTPadapter.java
  src/main/java/framework/api/services/cat/CatServiceManager.java
  src/main/java/framework/api/services/omdb/OmdbServiceManager.java
  src/test/java/framework/api/services/cat/GetFact_api_test.java
  src/test/java/framework/api/services/omdb/GetTitle_api_test.java
  src/test/java/framework/behaviordriven/services/cat/StepDefinitionsCat.java
Labels: code

#11 Facade strategy pattern
  src/main/java/framework/api/ApiManagementInterface.java
  src/main/java/framework/api/UriRequest.java
  src/main/java/framework/api/misc/AvailableApiServices.java
  src/main/java/framework/api/misc/CatApiTerms.java
  src/main/java/framework/api/misc/OmdbApiTerms.java
  src/main/java/framework/api/services/ApiServiceManager.java
  src/main/java/framework/api/services/cat/CatServiceManager.java
  src/main/java/framework/api/services/cat/CatUriRequest.java
  src/main/java/framework/api/services/omdb/OmdbServiceManager.java
  src/main/java/framework/api/services/omdb/OmdbUriRequest.java
  src/test/java/framework/api/services/cat/GetFact_api_test.java
  src/test/java/framework/api/services/omdb/GetTitle_api_test.java
  src/test/java/framework/behaviordriven/services/cat/StepDefinitionsCat.java
  src/test/java/framework/frontend/pages/wikipedia/SearchWikipedia_fe_test.java
  src/test/java/framework/tags/TestcaseTags.java
Labels: code

#12 Jacoco
  .github/workflows/gradle.yml
  build.gradle
Labels: configuration, gradle

#13 added xml test implementation
  .github/workflows/gradle.yml
  src/main/java/framework/adapters/HTTPadapter.java
  src/main/java/framework/api/ApiManagementInterface.java
  src/main/java/framework/api/services/ApiServiceManager.java
  src/main/java/framework/api/services/cat/CatServiceManager.java
  src/main/java/framework/api/services/omdb/OmdbServiceManager.java
  src/main/java/framework/utils/JsonUtils.java
  src/main/java/framework/utils/XmlUtils.java
  src/main/resources/api.secrets.properties
  src/test/java/framework/api/services/omdb/GetTitle_json_api_test.java
  src/test/java/framework/api/services/omdb/GetTitle_xml_api_test.java
Labels: code, configuration

#14 Version test
  .github/workflows/release.yml
Labels: configuration

#16 Release/1.1
  .github/label-pr.yml
  .github/workflows/gradle.yml
  .github/workflows/release.yml
  .gitignore
  README.md
  build.gradle
  gradle.properties
  src/main/java/framework/adapters/HTTPadapter.java
  src/main/java/framework/api/ApiManagementInterface.java
  src/main/java/framework/api/UriRequest.java
  src/main/java/framework/api/misc/AvailableApiServices.java
  src/main/java/framework/api/misc/CatApiTerms.java
  src/main/java/framework/api/misc/OmdbApiTerms.java
  src/main/java/framework/api/services/ApiServiceManager.java
  src/main/java/framework/api/services/cat/CatServiceManager.java
  src/main/java/framework/api/services/cat/CatUriRequest.java
  src/main/java/framework/api/services/omdb/OmdbServiceManager.java
  src/main/java/framework/api/services/omdb/OmdbUriRequest.java
  src/main/java/framework/frontend/WebdriverFactory.java
  src/main/java/framework/utils/JsonUtils.java
  src/main/java/framework/utils/PropertyUtils.java
  src/main/java/framework/utils/XmlUtils.java
  src/main/resources/api.secrets.properties
  src/main/resources/env.produktion.api.properties
  src/test/java/framework/api/services/cat/GetFact_api_test.java
  src/test/java/framework/api/services/omdb/GetTitle_json_api_test.java
  src/test/java/framework/api/services/omdb/GetTitle_xml_api_test.java
  src/test/java/framework/behaviordriven/services/cat/StepDefinitionsCat.java
  src/test/java/framework/frontend/pages/wikipedia/SearchWikipedia_fe_test.java
  src/test/java/framework/tags/TestcaseTags.java
Labels: code, configuration, documentation, gradle
